// <auto-generated />
using System;
using DatabaseModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseModel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411102251_editvalidation")]
    partial class editvalidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("PK__admins__3213E83FD7400FA3");

                    b.HasIndex(new[] { "Email" }, "UQ__admins__AB6E6164ACC71181")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__conversa__3213E83F45A250DF");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("ShowroomId")
                        .HasColumnType("int")
                        .HasColumnName("showroom_id");

                    b.Property<int?>("VisitorId")
                        .HasColumnType("int")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("PK__feedback__3213E83F0CFB4660");

                    b.HasIndex("ShowroomId");

                    b.HasIndex("VisitorId");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("PK__messages__3213E83FE3D9BC92");

                    b.HasIndex("ConversationId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("new_visitor")
                        .HasColumnName("type");

                    b.Property<int?>("VisitorId")
                        .HasColumnType("int")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("PK__notifica__3213E83F37B352C3");

                    b.HasIndex("VisitorId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_ar");

                    b.HasKey("Id")
                        .HasName("PK__products__3213E83FCDCD56FD");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int?>("ShowroomId")
                        .HasColumnType("int")
                        .HasColumnName("showroom_id");

                    b.HasKey("Id")
                        .HasName("PK__salesper__3213E83F7032FF32");

                    b.HasIndex("ShowroomId");

                    b.ToTable("salespersons", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Showroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_ar");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("PK__showroom__3213E83F53ABF816");

                    b.ToTable("showrooms", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpr");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("FollowUpStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("pending")
                        .HasColumnName("follow_up_status");

                    b.Property<bool?>("IsInterested")
                        .HasColumnType("bit")
                        .HasColumnName("is_interested");

                    b.Property<bool?>("IsReturning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_returning");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("int")
                        .HasColumnName("salesperson_id");

                    b.Property<int?>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<int>("ShowroomId")
                        .HasColumnType("int")
                        .HasColumnName("showroom_id");

                    b.Property<DateTimeOffset?>("VisitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("visited_at")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.HasKey("Id")
                        .HasName("PK__visitors__3213E83FA75E536F");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalespersonId");

                    b.HasIndex("ShowroomId");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("DatabaseModel.Models.Feedback", b =>
                {
                    b.HasOne("DatabaseModel.Models.Showroom", "Showroom")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ShowroomId")
                        .IsRequired()
                        .HasConstraintName("FK__feedback__showro__797309D9");

                    b.HasOne("DatabaseModel.Models.Visitor", "Visitor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("VisitorId")
                        .HasConstraintName("FK__feedback__visito__787EE5A0");

                    b.Navigation("Showroom");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("DatabaseModel.Models.Message", b =>
                {
                    b.HasOne("DatabaseModel.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__messages__conver__02FC7413");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DatabaseModel.Models.Notification", b =>
                {
                    b.HasOne("DatabaseModel.Models.Visitor", "Visitor")
                        .WithMany("Notifications")
                        .HasForeignKey("VisitorId")
                        .HasConstraintName("FK__notificat__visit__7F2BE32F");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("DatabaseModel.Models.Salesperson", b =>
                {
                    b.HasOne("DatabaseModel.Models.Showroom", "Showroom")
                        .WithMany("Salespeople")
                        .HasForeignKey("ShowroomId")
                        .HasConstraintName("FK__salespers__showr__6A30C649");

                    b.Navigation("Showroom");
                });

            modelBuilder.Entity("DatabaseModel.Models.Visitor", b =>
                {
                    b.HasOne("DatabaseModel.Models.Product", "Product")
                        .WithMany("Visitors")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__visitors__produc__73BA3083");

                    b.HasOne("DatabaseModel.Models.Salesperson", "Salesperson")
                        .WithMany("Visitors")
                        .HasForeignKey("SalespersonId")
                        .HasConstraintName("FK__visitors__salesp__74AE54BC");

                    b.HasOne("DatabaseModel.Models.Showroom", "Showroom")
                        .WithMany("Visitors")
                        .HasForeignKey("ShowroomId")
                        .IsRequired()
                        .HasConstraintName("FK__visitors__showro__72C60C4A");

                    b.Navigation("Product");

                    b.Navigation("Salesperson");

                    b.Navigation("Showroom");
                });

            modelBuilder.Entity("DatabaseModel.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DatabaseModel.Models.Product", b =>
                {
                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseModel.Models.Salesperson", b =>
                {
                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseModel.Models.Showroom", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Salespeople");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseModel.Models.Visitor", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
